[tool.poetry]
name = "darwin-py-test"
version = "0.9.3" # update this when you change the version - See: https://peps.python.org/pep-0440/
description = "Library and command line interface for darwin.v7labs.com"
homepage = "https://docs.v7labs.com/reference/getting-started-2"
documentation = "https://darwin-py-sdk.v7labs.com/index.html"
repository = "https://github.com/v7labs/darwin-py"
authors = ["V7 <info@v7labs.com>"]
readme = "README.md"
license = "MIT"

keywords = []
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License"]

packages = [
    { include = "darwin" },
]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.11"
argcomplete = "^2.0.0"
humanize = "^4.4.0"
numpy = "^1.24.1"
pillow = "^9.4.0"
pyyaml = ">=5.1"
requests = "^2.28.1"
rich = "^13.0.1"
dataclasses = {markers = "python_version < \"3.7\"", version = "^0.8"}
upolygon = "0.1.8"
jsonschema = "3.2.0"
deprecation = "^2.1.0"
pydantic = "^1.10.4"
orjson = "^3.8.5"

[tool.poetry.extras]

test = ["responses", "pytest", "pytest-describe", "scikit-learn"]
dev = ["black", "flake8", "isort", "mypy", "responses", "pytest", "pytest-describe", "scikit-learn"]
ml = ["scikit-learn", "torch", "torchvision"]
medical = ["nibabel", "connected-components-3d"]

[tool.poetry.group]

[tool.poetry.group.dev.dependencies]
black = {markers = "python_version > \"3.9\"", version = "^22.12.0"}
isort = {markers = "python_version > \"3.9\"", version = "^5.11.4"}
mypy = {markers = "python_version > \"3.9\"", version = "^0.991"}
response = {markers = "python_version > \"3.9\"", version = "^0.5.0"}
pytest = {markers = "python_version > \"3.9\"", version = "^7.2.0"}
pytest-describe = {markers = "python_version > \"3.9\"", version = "^2.0.1"}
scikit-learn = {markers = "python_version > \"3.9\"", version ="^1.2.0"}
flake8 = {markers = "python_version > \"3.9\"", version = "^6.0.0"}
flake8-pyproject = {markers = "python_version > \"3.9\"", version = "^1.2.2"}

[tool.poetry.scripts]
darwin = "darwin.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

#  TOOL SETTINGS

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
disallow_any_unimported = true
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = true
disallow_any_generics = false
disallow_subclassing_any = true
python_version = "3.10"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_return_any = false
warn_unreachable = true
pretty = true

[tool.black]
line-length = 160

[tool.flake8]
max-line-length = 160